### ISSUE TITLE
nested array of records not able to generate go files properly

### ISSUE THREAD

**Issue by rmanojcit** [alanctgardner/gogen-avro#6] opened 2016-08-04 12:19 UTC
When I try to generate go files for schema without nested array like one below it works as expected 

```
{
    "name": "Parent",
    "type":"record",
    "fields":[
        {
            "name":"children",
            "type":{
                "name":"Child",
                "type":"record",
                "fields":[
                    {"name":"name", "type":"string"}
                ]
            }
        }
    ] 
}
```

For the schema mentioned above gogen-avro is able to  generate the structs below as expected 

```
type Parent struct {
    Children *Child
}
type Child struct {
    Name string
}

```

But when make the schema to consist of an array of records like 

```
{
   "name":"Parent",
   "type":"record",
   "fields":[
      {
         "name":"children",
         "type":{
            "type":"array",
            "items":{
               "name":"Child",
               "type":"record",
               "fields":[
                  {
                     "name":"name",
                     "type":"string"
                  }
               ]
            }
         }
      }
   ]
}
```

gogen-avro  generates a struct like 

```
type Parent struct {
    Children []*Record
}
```

I would expect it to be something like the below structs instead

```

type Parent struct {
Children []*Child
}
type Child struct {
Name string
}
```

Please look into it and let me know if you require any further details or if I am missing something

**Comment by alanctgardner** [comment] 2016-08-20 02:10
Hi @rmanojcit! Thanks for the detailed issue, I was able to create an integration test for your schema and confirm this was an issue.

I've fixed the problem in master, arrays of records are now correctly serialized and deserialized. Let me know if you have any further issues, or feel free to close this issue if things are working for you.

**Comment by alanctgardner** [comment] 2016-12-29 23:30
I'm closing this issue to tidy things up, feel free to re-open it if the problem isn't resolved.

**Closed by alanctgardner** 2016-12-29 23:30 UTC
